# liux99/mule-openshift
FROM liux99/mule-ee:latest

MAINTAINER XIN LIU <xin.liu@perficient.com >

ENV MULE_VERSION 3.9.0
ENV MAVEN_VERSION=3.5.2

 


ADD  ./target/helloopenshift-1.0.0-SNAPSHOT-mule-application.jar /opt/mule-standalone-${MULE_VERSION}/apps/